### ISSUE TITLE
Hover expansion does not work anymore in current Beta 

### ISSUE THREAD

**Issue by Tyde** [TanzNukeTerror/Compact-FirefoxCSS#1]
If I hover over the collapsed sidebar in the current beta 72.0b7 it will not expand anymore. When I click on root tabs, it will open though. Do you have an idea where I could look for the root issue?

**Comment by TanzNukeTerror** [comment]
I don't use the beta, as things change too often for me to keep up. But I'll check it out and see what I can do. (No promise on speed, some stuff has come up and my attention is divided.)

**Comment by Tyde** [comment]
Using this: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover I've found that adding `z-index: 2;`for the collapsed state and `z-index: 1;` in the hovered state fixed the issue

**Comment by TanzNukeTerror** [comment]
Weird! I'll implement that change.

I've added it, if you could test and confirm that it works, I can mark this as closed.
